### ISSUE TITLE
Problem with skip line <br />

### ISSUE THREAD

**Issue by BaguetteV1** [chriskonnertz/bbcode#12]
Hello, I have a problem, I use this script for "translate" my bbcode to html but here is my text:

```
[b] Test 1 [/b]

[b] Test 2 [/b]
```

Echo:

```
Test1
<br />
Test2
```

(I put in code else br / is translate to line skip, Test1 & 2 are nicely bold)

**Comment by chriskonnertz** [comment]
Hi, so you are saying there is only one line break (`<br>`)  but you expect two?

**Comment by BaguetteV1** [comment]
Ok so, in my DB i have this (Line break between):
![image](https://user-images.githubusercontent.com/48206804/57091955-a5c89f80-6d0a-11e9-9808-276d0e5b5cf7.png)


I take this from a variable, and with your function i "translate" him to html, after i echo my translated text and it echo this (With unknown <br />):

![image](https://user-images.githubusercontent.com/48206804/57091924-8c275800-6d0a-11e9-9d60-1adb34d758d1.png)

**Comment by BaguetteV1** [comment]
Can you help me please ?

**Comment by BaguetteV1** [comment]
Sorry, I found the solution, the problem was i just une nl2br ^^
