### ISSUE TITLE
Ability to resize img sizes

### ISSUE THREAD

**Issue by copvampire** [chriskonnertz/bbcode#13]
When doing an image tag without width or height, it works fine. But with either one or both(to allow custom image sizes), it seems to not like it, could this be added?

**Comment by M4ko1339** [comment]
`case self::TAG_NAME_IMG:
                if ($tag->opening) {
                    if($tag->property) {
                        list($sizex, $sizey) = explode("x", $tag->property);
                
                        $code = '<img width="' . $sizex . '" height="' . $sizey . '" src="';
                    }
                    else {
                        $code = '<img src="';
                    }
                } else {
                    $code = '" />';
                }
                break;`

This should fix your problem.

**Comment by chriskonnertz** [comment]
Thanks @M4ko1339 😄👍
