### ISSUE TITLE
Issue with BBCode.

### ISSUE THREAD

**Issue by ui0ppk** [chriskonnertz/bbcode#23]
This library has a big issue, if you for example use the bbcode "font", you can add other css to the tag by closing the first one. 
`[font=Arial; background-color: green;]Example[/font]`
I may come up with a pull request fixing this issue.

**Comment by chriskonnertz** [comment]
Hello,

thanks that would be great!!

**Comment by Merulast** [comment]
I would recommend to never allow semicollons inside parameters.

**Comment by ui0ppk** [comment]
> I would recommend to never allow semicollons inside parameters.

Yeah like str_replace

**Comment by Merulast** [comment]
well you could just replace it or throw an exception. Whatever works better. But in both cases it's a fast way to solve things and to be honest, there is no reason in bbcode to allow `;` - if ppl need to add splitable syntax they have plenty other characters to choose from

**Comment by ui0ppk** [comment]
ill close this as its already complete lmao
