### ISSUE TITLE
Overwriting existing tags?

### ISSUE THREAD

**Issue by roberttolton** [chriskonnertz/bbcode#5]
Currently it doesn't look possible to overwrite any existing tags, to customise them?

**Comment by chriskonnertz** [comment]
Hello,

I will give you an answer later this day.

However, I want to mention that I started to rewrite the whole library.

**Comment by chriskonnertz** [comment]
v1.x: Not possible
v2.x: Will be implemented ( https://github.com/chriskonnertz/bbcode/issues/6 )
