### ISSUE TITLE
Embedded YouTube video incompatible with HTTPS pages (mixed content)

### ISSUE THREAD

**Issue by dracenmarx** [chriskonnertz/bbcode#7]
In the source code, you can find `http://www.youtube.com/embed/`

If you embed this in a HTTPS page, the embedded video will not load because the browser blocks mixed content.

You can solve this by writing `https://www.youtube.com/embed/`

**Comment by chriskonnertz** [comment]
Hello,

thank you, you are right. I have changed the protocol of the URL to `https`.

https://github.com/chriskonnertz/bbcode/commit/d3acd447ee11265d4ef38b9058cef32adcafa245
